"""add_is_personal_to_profile

Revision ID: 09dd80fcee38
Revises: 6a8aa043491d
Create Date: 2025-12-23 21:19:05.555503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dd80fcee38'
down_revision: Union[str, Sequence[str], None] = '6a8aa043491d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('is_personal', sa.Boolean(), nullable=True))
    op.execute("UPDATE profiles SET is_personal = False")
    op.alter_column('profiles', 'is_personal', nullable=False)
    op.create_index(op.f('ix_profiles_is_personal'), 'profiles', ['is_personal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_is_personal'), table_name='profiles')
    op.drop_column('profiles', 'is_personal')
    # ### end Alembic commands ###
