"""forum_hierarchy_and_stats

Revision ID: 5c39ba489184
Revises: 09dd80fcee38
Create Date: 2025-12-23 22:16:02.013047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c39ba489184'
down_revision: Union[str, Sequence[str], None] = '09dd80fcee38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_categories', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('forum_categories', sa.Column('icon_path', sa.String(length=1024), nullable=True))
    op.add_column('forum_categories', sa.Column('banner_path', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_forum_categories_parent_id'), 'forum_categories', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'forum_categories', 'forum_categories', ['parent_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('forum_threads', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('forum_threads', sa.Column('reply_count', sa.Integer(), nullable=True))
    op.add_column('forum_threads', sa.Column('is_sticky', sa.Boolean(), nullable=True))
    
    op.execute("UPDATE forum_threads SET view_count = 0, reply_count = 0, is_sticky = False")
    
    op.alter_column('forum_threads', 'view_count', nullable=False)
    op.alter_column('forum_threads', 'reply_count', nullable=False)
    op.alter_column('forum_threads', 'is_sticky', nullable=False)
    
    op.create_index(op.f('ix_forum_threads_is_sticky'), 'forum_threads', ['is_sticky'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_threads_is_sticky'), table_name='forum_threads')
    op.drop_column('forum_threads', 'is_sticky')
    op.drop_column('forum_threads', 'reply_count')
    op.drop_column('forum_threads', 'view_count')
    op.drop_constraint(None, 'forum_categories', type_='foreignkey')
    op.drop_index(op.f('ix_forum_categories_parent_id'), table_name='forum_categories')
    op.drop_column('forum_categories', 'banner_path')
    op.drop_column('forum_categories', 'icon_path')
    op.drop_column('forum_categories', 'parent_id')
    # ### end Alembic commands ###
