"""Add advanced profile attributes and Story model

Revision ID: 6a8aa043491d
Revises: 96be264b314b
Create Date: 2025-12-22 17:12:15.496251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8aa043491d'
down_revision: Union[str, Sequence[str], None] = '96be264b314b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_user_id'), 'stories', ['user_id'], unique=False)
    op.add_column('media', sa.Column('is_original', sa.Boolean(), nullable=False))
    op.add_column('profiles', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('build', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('hiv_status', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('privacy_mode', sa.String(length=50), nullable=False))
    op.add_column('profiles', sa.Column('is_trans_interested', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_trans_interested')
    op.drop_column('profiles', 'privacy_mode')
    op.drop_column('profiles', 'hiv_status')
    op.drop_column('profiles', 'build')
    op.drop_column('profiles', 'position')
    op.drop_column('media', 'is_original')
    op.drop_index(op.f('ix_stories_user_id'), table_name='stories')
    op.drop_table('stories')
    # ### end Alembic commands ###
