"""expand profile schema for social features

Revision ID: 8f54cf5f0ff8
Revises: 92c9bfa12002
Create Date: 2025-12-24 02:04:21.667947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8f54cf5f0ff8"
down_revision: Union[str, Sequence[str], None] = "92c9bfa12002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("display_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "profiles", sa.Column("pronouns", sa.String(length=50), nullable=True)
    )
    op.add_column("profiles", sa.Column("birthdate", sa.Date(), nullable=True))
    op.add_column(
        "profiles", sa.Column("gender_identity", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "profiles",
        sa.Column("relationship_status", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "profiles",
        sa.Column(
            "looking_for", postgresql.ARRAY(sa.String(length=100)), nullable=True
        ),
    )
    op.add_column(
        "profiles", sa.Column("occupation", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "profiles", sa.Column("industry", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "profiles", sa.Column("education_level", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "profiles", sa.Column("university", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "profiles",
        sa.Column(
            "social_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "profiles",
        sa.Column(
            "privacy_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_profiles_display_name"), "profiles", ["display_name"], unique=False
    )
    op.create_index(
        op.f("ix_profiles_gender_identity"),
        "profiles",
        ["gender_identity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profiles_industry"), "profiles", ["industry"], unique=False
    )
    op.create_index(
        op.f("ix_profiles_relationship_status"),
        "profiles",
        ["relationship_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profiles_relationship_status"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_industry"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_gender_identity"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_display_name"), table_name="profiles")
    op.drop_column("profiles", "privacy_settings")
    op.drop_column("profiles", "social_links")
    op.drop_column("profiles", "university")
    op.drop_column("profiles", "education_level")
    op.drop_column("profiles", "industry")
    op.drop_column("profiles", "occupation")
    op.drop_column("profiles", "looking_for")
    op.drop_column("profiles", "relationship_status")
    op.drop_column("profiles", "gender_identity")
    op.drop_column("profiles", "birthdate")
    op.drop_column("profiles", "pronouns")
    op.drop_column("profiles", "display_name")
    # ### end Alembic commands ###
