"""personal_posts_and_follows

Revision ID: 92c9bfa12002
Revises: 5c39ba489184
Create Date: 2025-12-24 00:32:22.072961

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "92c9bfa12002"
down_revision: Union[str, Sequence[str], None] = "5c39ba489184"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personal_posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("category_slug", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("media_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("follow_count", sa.Integer(), nullable=False),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_personal_posts_author_id"),
        "personal_posts",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_posts_category_slug"),
        "personal_posts",
        ["category_slug"],
        unique=False,
    )
    op.create_table(
        "personal_post_comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["personal_post_comments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["post_id"], ["personal_posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_personal_post_comments_author_id"),
        "personal_post_comments",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_post_comments_parent_id"),
        "personal_post_comments",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_post_comments_post_id"),
        "personal_post_comments",
        ["post_id"],
        unique=False,
    )
    op.create_table(
        "personal_post_followers",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["personal_posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "post_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("personal_post_followers")
    op.drop_index(
        op.f("ix_personal_post_comments_post_id"), table_name="personal_post_comments"
    )
    op.drop_index(
        op.f("ix_personal_post_comments_parent_id"), table_name="personal_post_comments"
    )
    op.drop_index(
        op.f("ix_personal_post_comments_author_id"), table_name="personal_post_comments"
    )
    op.drop_table("personal_post_comments")
    op.drop_index(op.f("ix_personal_posts_category_slug"), table_name="personal_posts")
    op.drop_index(op.f("ix_personal_posts_author_id"), table_name="personal_posts")
    op.drop_table("personal_posts")
    # ### end Alembic commands ###
